// <auto-generated />
using System;
using GestiuneCD.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestiuneCD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211020193809_FifthMigration")]
    partial class FifthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GestiuneCD.Domain.CD", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<short>("dimensiuneMB")
                        .HasColumnType("smallint");

                    b.Property<int>("nrDeSesiuni")
                        .HasColumnType("int");

                    b.Property<string>("nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("spatiuOcupat")
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte>("tip")
                        .HasColumnType("TINYINT");

                    b.Property<int>("vitezaDeInscriptionare")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CDs");
                });

            modelBuilder.Entity("GestiuneCD.Models.Entities.Sesiune", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("endDateTime")
                        .HasColumnType("DATETIME");

                    b.Property<int>("idCD")
                        .HasColumnType("int");

                    b.Property<DateTime?>("startDateTime")
                        .HasColumnType("DATETIME");

                    b.Property<int>("statusSesiune")
                        .HasColumnType("int");

                    b.Property<byte>("tipSesiune")
                        .HasColumnType("TINYINT");

                    b.HasKey("id");

                    b.HasIndex("idCD");

                    b.ToTable("Sesiuni");
                });

            modelBuilder.Entity("GestiuneCD.Models.Entities.Sesiune", b =>
                {
                    b.HasOne("GestiuneCD.Domain.CD", "cd")
                        .WithMany()
                        .HasForeignKey("idCD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cd");
                });
#pragma warning restore 612, 618
        }
    }
}
